node {
    def app
    stage "Prepare environment"
        checkout scm
        app  = docker.build("widgetsdirect", "WidgetsDirect")

    stage "Test and validate"
        app.withRun('-u root') {
            sh "echo Testing..."
            sh 'printf "_system\nSYS\n zn \"WidgetsDirect\" do ##class(UnitTest.Trak).RunRecursive() do ##class(UnitTest.Manager).OutputResultsXml(\"/tmp/test.xml\")" >>temp.cmd'
			//sh "ccontrol start CACHE"
            sh "csession CACHE <temp.cmd"
			//sh "ccontrol stop CACHE"
            junit "/tmp/test.xml"
        }
        
}