node {
    def app
    stage "Prepare environment"
        checkout scm
        app  = docker.build("widgetsdirect", "-f WidgetsDirect/Dockerfile")

    stage "Test and validate"
        app.inside {
            sh "echo Testing..."
            //junit 'reports/**/*.xml'
        }
}